In [14]:
#numpy is a library that allows for the use of arrays and matrices in python code
import numpy as np

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [16]:
type(a)

numpy.ndarray

Basic Operation of Array

In [17]:
print(a + b)    
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [18]:
#creating a 2D array
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [19]:
#creating a 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
print(b.shape) #(2,2,2) 2 arrays, 2 rows, 2 columns

(2, 2, 2)


In [21]:
print(a.ndim)

2


In [22]:
print(a.dtype)

int32


In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [25]:
np.random.randint(10,30, size=(3,3))

array([[17, 22, 24],
       [10, 22, 16],
       [22, 20, 25]])

In [26]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])

y = np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [28]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [ ]:
print(x.dot(y)) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [30]:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
x.prod() # it gives multiplication of all the elements of the array

12600

In [ ]:
x.mean() # it gives the mean of all the elements of the array

3.3333333333333335

In [33]:
x.mean(axis=0) # it gives the mean of each columns

array([4., 4., 2.])

In [34]:
x.mean(axis=1) # it gives the mean of each row

array([4., 3., 3.])

In [35]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) # it gives the variance of all the elements of the array
print(x.std()) # it gives the standard deviation of all the elements of the array

30
3.3333333333333335
1.8257418583505538


In [36]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) # it gives the 25th percentile of the array
print(np.percentile(a, 50)) # it gives the 50th percentile of the array
print(np.percentile(a, 75)) # it gives the 75th percentile of the array

3.0
5.0
7.0


In [39]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[16 44 46 49]
 [10 22 41 35]
 [11 35 20 12]
 [46 33 41 36]]


In [40]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 22]
 [41 35]
 [11 35]
 [20 12]
 [46 33]
 [41 36]]


In [41]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[16 44 46 49 10 22 41 35]
 [11 35 20 12 46 33 41 36]]


In [42]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [44]:
print(x[0])
print(x[0,0])

[7 2 3]
7


In [46]:
print(x[:3])
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[3 5 1]]
